apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: zookeeper-sgtc-release
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: zookeeper-sgtc-release-1
        spec:
            containers:
            - name: zookeeper-sgtc-release-1
              image: registry.my.com/zookeeper:3.3.6
              ports:
              - containerPort: 2181
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "1536Mi"
                  cpu: "500m"            
