apiVersion: v1
kind: Service
metadata:
    name: zookeeper-sgtc-release
spec: 
    ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
    selector:
      app: zookeeper-sgtc-release-1
