apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dubboadmin-sgtc-release
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: dubboadmin-sgtc-release-1
        spec:
            containers:
            - name: dubboadmin-sgtc-release
              image: registry.my.com/dubboadmin:2.5.4
              ports:
              - containerPort: 8080
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "1536Mi"
                  cpu: "300m"            
              env:
              - name: ZOOKEEPER
                value: 'zookeeper-sgtc-release'
