apiVersion: v1
kind: Service
metadata:
    name: dubboadmin-sgtc-release
spec:
    type: NodePort   
    ports:
    - port: 8080
      nodePort: 30011
    selector:
       app: dubboadmin-sgtc-release-1
